Added searchable filters in Ho_dan page
Cuuhomientrung/cuuhomientrung pull request #212
Opened 2020-11-03 15:32 UTC by dshongphuc

Mình thêm tính năng Cho phép gõ tên trong phần lọc tỉnh/huyện/xã #209 trong page Hộ dân.
Mình test khá kĩ rồi nhưng nếu có vấn đề gì vui lòng cho mình biết để mình fix nhé reviewers. :)

2020-11-03 17:38 UTC, mihnsen requested changes
@dshongphuc Thanks for your hard work. I can see it in my local. However, there are few points we need to change before I can approve your PR:
- Code convention: CSS and JS - please take a look at my comments.
- We should have no search when select "status"
- Package-lock.json is totally changed, can you validate it, please? 
- Translate choices.js 
  + No result found => Không tìm thấy kết quả

2020-11-03 17:38 UTC, mihnsen commented on .env.sample
> -DB_USER=postgres
@dshongphuc I don't see any reason we have to include the change of configuration example in this pull request. Can you exclude it?

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +      &:focus{ outline: 1px solid #9fcfff!important; }
@dshongphuc Can you break it down to a new line here please? It should be
```
      &:focus { 
            outline: 1px solid #9fcfff!important; 
      }
```

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +  .choices{
Can you add a space before curlybraces please? it should be `.choices {`

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +      &.is-focused{
Add space

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +          .choices__inner{ border-radius: 0.25rem 0.25rem 0 0; }
Break new line

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +      .choices__inner{
Add space

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +          background:#f8f9fa;
Add space after `:`

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +          &::after{
Add space

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +          .choices__item{
Add space

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +          width:100%;
Add space after `:`

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +      &__list--dropdown{
Add space

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +              width:100%;
Add space after `:`

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +
Remove empty line

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +
Remove empty line

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +    let selectTinh = new Choices(document.getElementById('select-tinh'));
The variable `selectTinh` is not used anywhere?

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +
Remove line break please

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +    &>div{
This css is for spacing on mobile I guess
![image](https://user-images.githubusercontent.com/9761138/98019253-1981c600-1e34-11eb-8ac8-c38979cd13d3.png)
Can we change it by adding `mb-2` class to each column inside `.citizen-filter`?

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +    let selectStatus = new Choices(document.getElementById('select-status'));
In the issue, there is no requirement to add a search to select status and just a few items, we don't need search for status.

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
>  		});
I believe there is a `Tab` here, can you change it to space?

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/js/ho_dan.js
> +            let listXa = Object.keys(data).map(key => {
Missing `;` after each line of code

2020-11-03 17:38 UTC, mihnsen commented on project/app/static/webpack_sources/scss/pages/_hodan.scss
> +              &:focus{
Add space

2020-11-03 17:56 UTC, mihnsen commented
@dshongphuc anh mới hỏi bên cái issue related đến cái PR này: #209 
Thì các bạn đã định làm lại trang này theo cái issue: #208 
Em follow cái issue đó trước khi cập nhật PR không lại mất công nhé @dshongphuc

2020-11-04 14:44 UTC, dshongphuc commented
Hi anh @mihnsen,
Em đã fix các lỗi trong PR tối hôm qua : 
- [x] Code convention: CSS and JS
- [x] We should have no search when select "status"
- [x] Translate choices.js : No result found => Không tìm thấy kết quả

Tuy nhiên, chỉ có cái vấn đề với Package-lock.json là em chưa rõ lắm, lúc em cài package mới hoặc install các packages hiện có trong package.json, nó luôn báo : `this version of npm is compatible with lockfileversion@1, but package-lock.json was generated for lockfileversion@2` rồi sau đó generate ra file package-lock mới luôn. Anh có cách nào giải quyết vụ này ko anh? Hoặc anh thử chạy npm install bên máy anh xem có gặp vấn đề giống em ko? (em chạy bên trong docker luôn)

Thanks anh nhiều !

2020-11-05 23:14 UTC, mihnsen commented
@dshongphuc anh thấy các bạn định thay đổi model hộ dân. em xem thêm chi tiết ở đây nhé: https://github.com/Cuuhomientrung/cuuhomientrung/issues/208

2020-11-06 04:19 UTC, dshongphuc commented
hi anh @mihnsen , em đã thảo luận với bạn @kc97ble mấy hôm trước và bạn ấy đã confirm là issue này ko liên quan đến #208 ạ : https://github.com/Cuuhomientrung/cuuhomientrung/issues/209#issuecomment-721624746

2020-11-06 06:53 UTC, kc97ble commented
@mihnsen anh có thể review lại giúp em cái PR này không ạ? Nếu ổn thì ta có thể merge.

2020-11-06 08:22 UTC, merged